<%@ Page Title="Product Detail Page" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ManageProducts.aspx.cs" Inherits="ThinhStoreWF.Views.ManageProducts" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <div class="m-3">
        <asp:HyperLink runat="server" ID="btnCreate" CssClass="btn btn-primary" NavigateUrl="/Views/CreateProduct">
            <i class="fa fa-plus"></i> 
            Tạo mới
        </asp:HyperLink>
        <asp:DropDownList ID="ddlTypeFilter" runat="server">
            <asp:ListItem Value="">Loại sản phẩm</asp:ListItem>
            <asp:ListItem Value="acer">Acer</asp:ListItem>
            <asp:ListItem Value="asus">Asus</asp:ListItem>
            <asp:ListItem Value="msi">MSI</asp:ListItem>
            <asp:ListItem Value="accessory">Phụ kiện</asp:ListItem>
        </asp:DropDownList>
        <asp:TextBox ID="txtNameFilter" runat="server" placeholder="Tên sản phẩm"></asp:TextBox>
        <asp:Button CssClass="btn btn-primary" ID="btnFilter" runat="server" Text="Lọc" OnClick="btnFilter_Click" />
    </div>

    <asp:SqlDataSource ID="SqlDataSource1" runat="server"
        ConnectionString="<%$ ConnectionStrings:DBConnection %>" 
        SelectCommand="SELECT id, Name, Price, Type, Description, Image, discount, spec_os FROM Products" 
        DeleteCommand="DELETE FROM Products WHERE id = @id"
        UpdateCommand="UPDATE Products SET Name = @Name, Price = @Price, type = @type, Description = @Description, Image = @Image, discount = @discount, spec_os = @spec_os WHERE id = @id"
        InsertCommand="INSERT INTO Products (Name, Price, type, Description) VALUES (@Name, @Price, @type, @Description)">
        <DeleteParameters>
            <asp:Parameter Name="id" Type="Int32" />
        </DeleteParameters>
        <UpdateParameters>
            <asp:Parameter Name="Name" Type="String" />
            <asp:Parameter Name="Price" Type="String" />
            <asp:Parameter Name="type" Type="String" />
            <asp:Parameter Name="Description" Type="String" />
            <asp:Parameter Name="id" Type="Int32" />
        </UpdateParameters>
        <InsertParameters>
            <asp:Parameter Name="Name" Type="String" />
            <asp:Parameter Name="Price" Type="String" />
            <asp:Parameter Name="type" Type="String" />
            <asp:Parameter Name="Description" Type="String" />
        </InsertParameters>
    </asp:SqlDataSource>

    <asp:GridView ID="GridView1" CssClass="table table-striped color-table" runat="server" DataSourceID="SqlDataSource1" 
        AutoGenerateColumns="False" DataKeyNames="id" 
        AllowPaging="True" AllowSorting="True" AutoGenerateEditButton="false" AutoGenerateDeleteButton="false">
        <Columns>
            <asp:BoundField DataField="id" HeaderText="ID" ReadOnly="True" SortExpression="id" />
            <asp:BoundField DataField="name" HeaderText="Tên" SortExpression="name" />
            <asp:BoundField DataField="Price" HeaderText="Giá" SortExpression="Price" />
            <asp:BoundField DataField="type" HeaderText="Loại" SortExpression="type" />
            <asp:BoundField DataField="Image" HeaderText="Hình" SortExpression="image"/>
            <asp:BoundField DataField="discount" HeaderText="Giảm giá" SortExpression="discount"/>
            <asp:BoundField DataField="spec_os" HeaderText="OS" SortExpression="spec_os"/>

            
            <%--<asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />--%>
            <asp:CommandField ShowEditButton="true" />
            <asp:CommandField ShowDeleteButton="true" />

            <%--<asp:FileUpload ID="FileUpload1" runat="server" />
            <asp:Button ID="btnUpload" runat="server" Text="Upload" OnClick="btnUpload_Click" />--%>

        </Columns>
    </asp:GridView>
    <script>
        $(function () {
            $('.scroll').remove();
        })
    </script>
</asp:Content>
